### ISSUE TITLE
Windows clipboard doesn't work after selecting "GUID (variables)"

### ISSUE THREAD

**Issue by brandonaut** [01org/edkiibuilddataviewer#2]
After loading a build file, loading a report file, and selecting "GUID (variables)" as the view type, I can no longer paste text into any programs as long as EDKII Build Data Viewer is running. This makes it really hard to take the data (such as duplicate GUIDs) from EDKII Build Data Viewer and use it somewhere else.

**Comment by leehamel** [comment]
Fixed in release 1.0.2.4.
